// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/shortener/internal/service (interfaces: ShortURLIDGenerator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock-short-URL-ID-generator.gen.go -package=mocks . ShortURLIDGenerator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShortURLIDGenerator is a mock of ShortURLIDGenerator interface.
type MockShortURLIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLIDGeneratorMockRecorder
	isgomock struct{}
}

// MockShortURLIDGeneratorMockRecorder is the mock recorder for MockShortURLIDGenerator.
type MockShortURLIDGeneratorMockRecorder struct {
	mock *MockShortURLIDGenerator
}

// NewMockShortURLIDGenerator creates a new mock instance.
func NewMockShortURLIDGenerator(ctrl *gomock.Controller) *MockShortURLIDGenerator {
	mock := &MockShortURLIDGenerator{ctrl: ctrl}
	mock.recorder = &MockShortURLIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLIDGenerator) EXPECT() *MockShortURLIDGeneratorMockRecorder {
	return m.recorder
}

// CalculateShortURLID mocks base method.
func (m *MockShortURLIDGenerator) CalculateShortURLID(url string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateShortURLID", url)
	ret0, _ := ret[0].(string)
	return ret0
}

// CalculateShortURLID indicates an expected call of CalculateShortURLID.
func (mr *MockShortURLIDGeneratorMockRecorder) CalculateShortURLID(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateShortURLID", reflect.TypeOf((*MockShortURLIDGenerator)(nil).CalculateShortURLID), url)
}
