// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/shortener/internal/service (interfaces: ShortUrlIDGenerator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock-ShortUrlIDGenerator.go -package=mocks . ShortUrlIDGenerator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShortUrlIDGenerator is a mock of ShortUrlIDGenerator interface.
type MockShortUrlIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockShortUrlIDGeneratorMockRecorder
	isgomock struct{}
}

// MockShortUrlIDGeneratorMockRecorder is the mock recorder for MockShortUrlIDGenerator.
type MockShortUrlIDGeneratorMockRecorder struct {
	mock *MockShortUrlIDGenerator
}

// NewMockShortUrlIDGenerator creates a new mock instance.
func NewMockShortUrlIDGenerator(ctrl *gomock.Controller) *MockShortUrlIDGenerator {
	mock := &MockShortUrlIDGenerator{ctrl: ctrl}
	mock.recorder = &MockShortUrlIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortUrlIDGenerator) EXPECT() *MockShortUrlIDGeneratorMockRecorder {
	return m.recorder
}

// CalculateShortURLID mocks base method.
func (m *MockShortUrlIDGenerator) CalculateShortURLID(url string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateShortURLID", url)
	ret0, _ := ret[0].(string)
	return ret0
}

// CalculateShortURLID indicates an expected call of CalculateShortURLID.
func (mr *MockShortUrlIDGeneratorMockRecorder) CalculateShortURLID(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateShortURLID", reflect.TypeOf((*MockShortUrlIDGenerator)(nil).CalculateShortURLID), url)
}
