// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/shortener/internal/service (interfaces: URLServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock-url-service.go -package=mocks . URLServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/SergeyRG/shortener/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockURLServiceInterface is a mock of URLServiceInterface interface.
type MockURLServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockURLServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockURLServiceInterfaceMockRecorder is the mock recorder for MockURLServiceInterface.
type MockURLServiceInterfaceMockRecorder struct {
	mock *MockURLServiceInterface
}

// NewMockURLServiceInterface creates a new mock instance.
func NewMockURLServiceInterface(ctrl *gomock.Controller) *MockURLServiceInterface {
	mock := &MockURLServiceInterface{ctrl: ctrl}
	mock.recorder = &MockURLServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLServiceInterface) EXPECT() *MockURLServiceInterfaceMockRecorder {
	return m.recorder
}

// AddBatch mocks base method.
func (m *MockURLServiceInterface) AddBatch(ctx context.Context, data []service.BatchDataRequest) ([]service.BatchDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBatch", ctx, data)
	ret0, _ := ret[0].([]service.BatchDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBatch indicates an expected call of AddBatch.
func (mr *MockURLServiceInterfaceMockRecorder) AddBatch(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBatch", reflect.TypeOf((*MockURLServiceInterface)(nil).AddBatch), ctx, data)
}

// AddShortURL mocks base method.
func (m *MockURLServiceInterface) AddShortURL(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShortURL", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddShortURL indicates an expected call of AddShortURL.
func (mr *MockURLServiceInterfaceMockRecorder) AddShortURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShortURL", reflect.TypeOf((*MockURLServiceInterface)(nil).AddShortURL), ctx, url)
}

// GetOriginalURLByID mocks base method.
func (m *MockURLServiceInterface) GetOriginalURLByID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURLByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURLByID indicates an expected call of GetOriginalURLByID.
func (mr *MockURLServiceInterfaceMockRecorder) GetOriginalURLByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURLByID", reflect.TypeOf((*MockURLServiceInterface)(nil).GetOriginalURLByID), ctx, id)
}

// MakeShortURLByID mocks base method.
func (m *MockURLServiceInterface) MakeShortURLByID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeShortURLByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeShortURLByID indicates an expected call of MakeShortURLByID.
func (mr *MockURLServiceInterfaceMockRecorder) MakeShortURLByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeShortURLByID", reflect.TypeOf((*MockURLServiceInterface)(nil).MakeShortURLByID), ctx, id)
}
