// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/shortener/internal/service (interfaces: URLServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock-url-service.go -package=mocks . URLServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockURLServiceInterface is a mock of URLServiceInterface interface.
type MockURLServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockURLServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockURLServiceInterfaceMockRecorder is the mock recorder for MockURLServiceInterface.
type MockURLServiceInterfaceMockRecorder struct {
	mock *MockURLServiceInterface
}

// NewMockURLServiceInterface creates a new mock instance.
func NewMockURLServiceInterface(ctrl *gomock.Controller) *MockURLServiceInterface {
	mock := &MockURLServiceInterface{ctrl: ctrl}
	mock.recorder = &MockURLServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLServiceInterface) EXPECT() *MockURLServiceInterfaceMockRecorder {
	return m.recorder
}

// AddShortURL mocks base method.
func (m *MockURLServiceInterface) AddShortURL(url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShortURL", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddShortURL indicates an expected call of AddShortURL.
func (mr *MockURLServiceInterfaceMockRecorder) AddShortURL(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShortURL", reflect.TypeOf((*MockURLServiceInterface)(nil).AddShortURL), url)
}

// ExportRepoToJSONFile mocks base method.
func (m *MockURLServiceInterface) ExportRepoToJSONFile() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRepoToJSONFile")
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportRepoToJSONFile indicates an expected call of ExportRepoToJSONFile.
func (mr *MockURLServiceInterfaceMockRecorder) ExportRepoToJSONFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRepoToJSONFile", reflect.TypeOf((*MockURLServiceInterface)(nil).ExportRepoToJSONFile))
}

// GetOriginalURLByID mocks base method.
func (m *MockURLServiceInterface) GetOriginalURLByID(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURLByID", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURLByID indicates an expected call of GetOriginalURLByID.
func (mr *MockURLServiceInterfaceMockRecorder) GetOriginalURLByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURLByID", reflect.TypeOf((*MockURLServiceInterface)(nil).GetOriginalURLByID), id)
}

// MakeShortURLByID mocks base method.
func (m *MockURLServiceInterface) MakeShortURLByID(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeShortURLByID", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeShortURLByID indicates an expected call of MakeShortURLByID.
func (mr *MockURLServiceInterfaceMockRecorder) MakeShortURLByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeShortURLByID", reflect.TypeOf((*MockURLServiceInterface)(nil).MakeShortURLByID), id)
}
