// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/shortener/internal/service (interfaces: URLServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock-url-service.go -package=mocks . URLServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SergeyRG/shortener/internal/model"
	service "github.com/SergeyRG/shortener/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockURLServiceInterface is a mock of URLServiceInterface interface.
type MockURLServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockURLServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockURLServiceInterfaceMockRecorder is the mock recorder for MockURLServiceInterface.
type MockURLServiceInterfaceMockRecorder struct {
	mock *MockURLServiceInterface
}

// NewMockURLServiceInterface creates a new mock instance.
func NewMockURLServiceInterface(ctrl *gomock.Controller) *MockURLServiceInterface {
	mock := &MockURLServiceInterface{ctrl: ctrl}
	mock.recorder = &MockURLServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLServiceInterface) EXPECT() *MockURLServiceInterfaceMockRecorder {
	return m.recorder
}

// AddBatch mocks base method.
func (m *MockURLServiceInterface) AddBatch(ctx context.Context, data []service.BatchDataRequest, userID string) ([]service.BatchDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBatch", ctx, data, userID)
	ret0, _ := ret[0].([]service.BatchDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBatch indicates an expected call of AddBatch.
func (mr *MockURLServiceInterfaceMockRecorder) AddBatch(ctx, data, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBatch", reflect.TypeOf((*MockURLServiceInterface)(nil).AddBatch), ctx, data, userID)
}

// AddForDeleting mocks base method.
func (m *MockURLServiceInterface) AddForDeleting(ctx context.Context, data model.DeleteTaskDto) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddForDeleting", ctx, data)
}

// AddForDeleting indicates an expected call of AddForDeleting.
func (mr *MockURLServiceInterfaceMockRecorder) AddForDeleting(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddForDeleting", reflect.TypeOf((*MockURLServiceInterface)(nil).AddForDeleting), ctx, data)
}

// AddShortURL mocks base method.
func (m *MockURLServiceInterface) AddShortURL(ctx context.Context, url, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShortURL", ctx, url, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddShortURL indicates an expected call of AddShortURL.
func (mr *MockURLServiceInterfaceMockRecorder) AddShortURL(ctx, url, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShortURL", reflect.TypeOf((*MockURLServiceInterface)(nil).AddShortURL), ctx, url, userID)
}

// GetOriginalURLByID mocks base method.
func (m *MockURLServiceInterface) GetOriginalURLByID(ctx context.Context, id string) (model.ShortenModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURLByID", ctx, id)
	ret0, _ := ret[0].(model.ShortenModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURLByID indicates an expected call of GetOriginalURLByID.
func (mr *MockURLServiceInterfaceMockRecorder) GetOriginalURLByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURLByID", reflect.TypeOf((*MockURLServiceInterface)(nil).GetOriginalURLByID), ctx, id)
}

// GetURLByUserID mocks base method.
func (m *MockURLServiceInterface) GetURLByUserID(ctx context.Context, userID string) ([]service.UserURLData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByUserID", ctx, userID)
	ret0, _ := ret[0].([]service.UserURLData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByUserID indicates an expected call of GetURLByUserID.
func (mr *MockURLServiceInterfaceMockRecorder) GetURLByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByUserID", reflect.TypeOf((*MockURLServiceInterface)(nil).GetURLByUserID), ctx, userID)
}

// GetURLSCount mocks base method.
func (m *MockURLServiceInterface) GetURLSCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLSCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLSCount indicates an expected call of GetURLSCount.
func (mr *MockURLServiceInterfaceMockRecorder) GetURLSCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLSCount", reflect.TypeOf((*MockURLServiceInterface)(nil).GetURLSCount), ctx)
}

// GetUsersCount mocks base method.
func (m *MockURLServiceInterface) GetUsersCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersCount indicates an expected call of GetUsersCount.
func (mr *MockURLServiceInterfaceMockRecorder) GetUsersCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersCount", reflect.TypeOf((*MockURLServiceInterface)(nil).GetUsersCount), ctx)
}

// MakeShortURLByID mocks base method.
func (m *MockURLServiceInterface) MakeShortURLByID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeShortURLByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeShortURLByID indicates an expected call of MakeShortURLByID.
func (mr *MockURLServiceInterfaceMockRecorder) MakeShortURLByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeShortURLByID", reflect.TypeOf((*MockURLServiceInterface)(nil).MakeShortURLByID), ctx, id)
}
